[project]
name = "cc-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.97.0",
    "ipykernel>=7.2.0",
    "path>=17.1.1",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["src"]


[tool.ruff.lint.per-file-ignores]
"main.py" = ["E402"] # 忽略规则

[project.scripts]
evolve = "src.entry:main"  # 格式：终端命令 = 包.模块:函数名